// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ueqmdglrsrmbjojdyhhi.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVlcW1kZ2xyc3JtYmpvamR5aGhpIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDk5MDA5NTAsImV4cCI6MjA2NTQ3Njk1MH0.RcEBZDx67m-Smr24x4YmlKZcHBiveo0DUqpslSqoyZo";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);